title: "Sheevum Goel’s AI Tools Website"
description: "Showcasing innovative AI tools for business growth, focusing on no-code/low-code and affordable solutions."
author: "Sheevum Goel"
email: "your@email.com"
url: "https://sheevu.github.io/sheevum.github.io"
github_username: "sheevu"
show_excerpts: true
theme: jekyll-theme-modernist
